const sliderBlurbs = [
  {
    title       : "Louie Chat",
    slug        : "chat",
    icon        : "/images/icon-unlimited-chat.svg",
    maxWidth    : "90%",
    body        : "Unlimited chat with your healthcare assistant.  Get vetted answers to your healthcare questions and concerns.",
    more        : "Healthcare is complicated. We are here to help! With Orderly, you can simply text your questions about healthcare, just like you are texting a friend. Using multiple data sources, we can provide answers immediately to help you find the best doctor, the lowest price, or just help you better understand your benefits.",
  },
  {
    title       : "Price medications and services",
    slug        : "prices",
    icon        : "/images/icon-cost.svg",
    maxWidth    : null,
    body        : "Rest easy knowing what your medications and health services will cost you – all before pulling out your wallet.",
    more        : "Lipitor Blurb, with texts",
  },
  {
    title       : "Prescription discounts",
    slug        : "discounts",
    icon        : "/images/icon-discounts.svg",
    maxWidth    : null,
    body        : "You heard me right! I'll work hard to save you even more money by locating discounts on medications in your area.",
    more        : "Lipitor Blurb, with texts",
  },
  {
    title       : "Find highly rated doctors",
    slug        : "find-doctors",
    icon        : "/images/icon-highly-rated.svg",
    maxWidth    : null,
    body        : "You heard me right! I'll work hard to save you even more money by locating discounts on medications in your area.",
    more        : "Lipitor Blurb, with texts",
  },
  {
    title       : "Shop for the best Insurence Plan",
    slug        : "shop-insurence",
    icon        : "/images/icon-insurance-plan.svg",
    maxWidth    : null,
    body        : "Searching for the perfect plan can feel like a chore. I'll make it easy by connecting you with our partners.",
    more        : "Plan Blurb, with texts",
  },
  {
    title       : "Stellar Support",
    slug        : "human-support",
    icon        : "/images/icon-human-support.svg",
    maxWidth    : null,
    body        : "I'll make sure that a live human is ready to jump in",
    more        : "Lipitor Blurb, with texts",
  },
  {
    title       : "Virtual Doctor Visits",
    slug        : "virtual-doc",
    icon        : "/images/icon-virtual-doc-visit.svg",
    maxWidth    : null,
    body        : "I'll connect you with Colorado licensed doctors *",
    more        : "Virtually visit with Colorado licensed doctors to receive referrals, prescriptions, or review health concerns. *These services are only available to residents of Colorado at this time.",
  },
  {
    title       : "Urgent Care Solutions",
    slug        : "urgent-care",
    icon        : "/images/icon-ambulance.svg",
    maxWidth    : null,
    body        : "I'll provide on demand Urgent Care solutions *",
    more        : "Emergencies happen, and I'm here to help. I'll get you connected to our ER partners quickly and efficiently. *These services are only available to residents of Colorado at this time.",
  },
];

module.exports = sliderBlurbs;
